### ISSUE TITLE
Consider rewording language around CLAs

### ISSUE THREAD

**Issue by hiimbex** [mntnr/audit-templates#1]
Love this template! My one piece of feedback is that the wording around CLAs seems to strongly support them and stress their need legally; however, I have recently heard many good arguments against them. Here's a longer form more explanative version of why: https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/.

**Comment by RichardLitt** [comment]
That's good feedback! 

I generally don't actually support their usage, either, but I find that larger companies tend to go for them. It might make more sense to just remove the clause altogether, and if there is a CLA, bring it up in the check. Let's go with that.
