### ISSUE TITLE
Confusing (possibly outdated?) instructions to audit client

### ISSUE THREAD

**Issue by schroedey** [mntnr/audit-templates#10]
I'm not sure what "For notes on anything crossed out, look below." means.  I don't recall seeing crossed out items in the audits I've looked at.  Is crossing stuff out part of the current workflow?  Also, "below" is non-specific - where below?  (TODO section?  Somewhere else?)

**Comment by RichardLitt** [comment]
To cross out a comment in Markdown, use `~~double tildes~~`. Instead of deleting lines, it may be better to ~~cross them out~~.

**Comment by schroedey** [comment]
So if a particular audit check item doesn't apply, cross it out?  If so, that works for me.  (However, I'm only applying this to the audit sections up to (but not including) the TODO section - items that don't apply in the Generic and Issues sections seem totally unnecessary to retain, so my intention is to delete them.)

**Comment by RichardLitt** [comment]
Yeah. You got it.
