### ISSUE TITLE
Code of Conduct example link is broken

### ISSUE THREAD

**Issue by schroedey** [mntnr/audit-templates#5]
For this item: 

> Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covgen)?

the link to the Contributor Covenant 404s.  The correct link is currently: https://github.com/simonv3/covenant-generator

**Comment by RichardLitt** [comment]
Thanks. For this sort of thing, you can probably just open a quick PR. Want to do that to get into the practice of doing that?
